name: task_for_job
description: "Task For Job"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # CupertinoIcons
  cupertino_icons: ^1.0.2

  # for location features
  yandex_mapkit: ^3.3.3
  geolocator: ^10.1.0

  # state managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # code generators
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # for network
  dio: ^5.4.0

  # local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

#  assets:
#    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700